// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.ProtoEnum;

public enum chat_subcmd
    implements ProtoEnum {
  SUBCMD_ROOM_CHAT(1),
  /**
   * 直播房间聊天
   */
  SUBCMD_GET_POPUP_WORD_LIST(2),
  /**
   * 获取弹幕列表
   */
  SUBCMD_ZHUSHOU_ROOM_CHAT(3),
  /**
   * 助手聊天消息, 请求包内容和0x1一样
   */
  SUBCMD_MSPEED_ROOM_CHAT(4),
  /**
   * 移动飞车电视台, 请求包内容和0x1一样
   */
  SUBCMD_HLDDZ_ROOM_CHAT(5),
  /**
   * 欢乐斗地主, 请求包内容和0x1一样
   */
  SUBCMD_PPKDC_ROOM_CHAT(6),
  /**
   * 跑跑卡丁车, 请求包内容和0x1一样
   */
  SUBCMD_HPJY_ROOM_CHAT(7);

  private final int value;

  private chat_subcmd(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
