// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.ProtoEnum;

public enum ChatErrCode
    implements ProtoEnum {
  ChatErrCode_Success(0),
  /**
   * 成功
   */
  ChatErrCode_SYSRERR(1),
  /**
   * 服务器内部错误
   */
  ChatErrCode_AUTHFAILD(2),
  /**
   * 没有聊天权限
   */
  ChatErrCode_Forbidden(3),
  /**
   * 已被禁言
   */
  ChatErrCode_Dirty(4);

  private final int value;

  private ChatErrCode(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
