// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.ProtoEnum;

public enum ChatOperationType
    implements ProtoEnum {
  ChatOperationType_Common(0),
  /**
   * 普通消息
   */
  ChatOperationType_Lottery(1);

  private final int value;

  private ChatOperationType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
