// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * ////////////////////////////////////////
 * 0x1010 0x2 获取弹幕列表 请求
 */
public final class GetPopupWordListReq extends Message {

  public static final ByteString DEFAULT_UID = ByteString.EMPTY;
  public static final ByteString DEFAULT_AREAID = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString uid;

  /**
   * 游戏uid
   */
  @ProtoField(tag = 2, type = BYTES, label = REQUIRED)
  public final ByteString areaid;

  public GetPopupWordListReq(ByteString uid, ByteString areaid) {
    this.uid = uid;
    this.areaid = areaid;
  }

  private GetPopupWordListReq(Builder builder) {
    this(builder.uid, builder.areaid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetPopupWordListReq)) return false;
    GetPopupWordListReq o = (GetPopupWordListReq) other;
    return equals(uid, o.uid)
        && equals(areaid, o.areaid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = uid != null ? uid.hashCode() : 0;
      result = result * 37 + (areaid != null ? areaid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetPopupWordListReq> {

    public ByteString uid;
    public ByteString areaid;

    public Builder() {
    }

    public Builder(GetPopupWordListReq message) {
      super(message);
      if (message == null) return;
      this.uid = message.uid;
      this.areaid = message.areaid;
    }

    public Builder uid(ByteString uid) {
      this.uid = uid;
      return this;
    }

    /**
     * 游戏uid
     */
    public Builder areaid(ByteString areaid) {
      this.areaid = areaid;
      return this;
    }

    @Override
    public GetPopupWordListReq build() {
      checkRequiredFields();
      return new GetPopupWordListReq(this);
    }
  }
}
