// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import java.util.Collections;
import java.util.List;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.INT32;
import static com.squareup.tga.Message.Label.REPEATED;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * 0x1010 0x2 获取弹幕列表 响应
 */
public final class GetPopupWordListRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final List<ByteString> DEFAULT_WORD_LIST = Collections.emptyList();

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer result;

  /**
   * 结果
   */
  @ProtoField(tag = 2, type = BYTES, label = REPEATED)
  public final List<ByteString> word_list;

  public GetPopupWordListRsp(Integer result, List<ByteString> word_list) {
    this.result = result;
    this.word_list = immutableCopyOf(word_list);
  }

  private GetPopupWordListRsp(Builder builder) {
    this(builder.result, builder.word_list);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetPopupWordListRsp)) return false;
    GetPopupWordListRsp o = (GetPopupWordListRsp) other;
    return equals(result, o.result)
        && equals(word_list, o.word_list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (word_list != null ? word_list.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetPopupWordListRsp> {

    public Integer result;
    public List<ByteString> word_list;

    public Builder() {
    }

    public Builder(GetPopupWordListRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.word_list = copyOf(message.word_list);
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 结果
     */
    public Builder word_list(List<ByteString> word_list) {
      this.word_list = checkForNulls(word_list);
      return this;
    }

    @Override
    public GetPopupWordListRsp build() {
      checkRequiredFields();
      return new GetPopupWordListRsp(this);
    }
  }
}
