// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * 直播房间聊天 回包
 */
public final class RoomChatRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final ByteString DEFAULT_ERRMSG = ByteString.EMPTY;
  public static final Integer DEFAULT_UNFORBID_TIMESTAMP = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  /**
   *
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString errmsg;

  /**
   * 错误信息
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer unforbid_timestamp;

  public RoomChatRsp(Integer result, ByteString errmsg, Integer unforbid_timestamp) {
    this.result = result;
    this.errmsg = errmsg;
    this.unforbid_timestamp = unforbid_timestamp;
  }

  private RoomChatRsp(Builder builder) {
    this(builder.result, builder.errmsg, builder.unforbid_timestamp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RoomChatRsp)) return false;
    RoomChatRsp o = (RoomChatRsp) other;
    return equals(result, o.result)
        && equals(errmsg, o.errmsg)
        && equals(unforbid_timestamp, o.unforbid_timestamp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (errmsg != null ? errmsg.hashCode() : 0);
      result = result * 37 + (unforbid_timestamp != null ? unforbid_timestamp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RoomChatRsp> {

    public Integer result;
    public ByteString errmsg;
    public Integer unforbid_timestamp;

    public Builder() {
    }

    public Builder(RoomChatRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.errmsg = message.errmsg;
      this.unforbid_timestamp = message.unforbid_timestamp;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     *
     */
    public Builder errmsg(ByteString errmsg) {
      this.errmsg = errmsg;
      return this;
    }

    /**
     * 错误信息
     */
    public Builder unforbid_timestamp(Integer unforbid_timestamp) {
      this.unforbid_timestamp = unforbid_timestamp;
      return this;
    }

    @Override
    public RoomChatRsp build() {
      checkRequiredFields();
      return new RoomChatRsp(this);
    }
  }
}
