// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat.proto
package com.tencent.protocol.tga.chat;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.INT32;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * 直播房间聊天 请求
 */
public final class RoomChatReq extends Message {

  public static final ByteString DEFAULT_USERID = ByteString.EMPTY;
  public static final ByteString DEFAULT_ROOMID = ByteString.EMPTY;
  public static final ByteString DEFAULT_NICK_NAME = ByteString.EMPTY;
  public static final ByteString DEFAULT_CHAT_MSG = ByteString.EMPTY;
  public static final ByteString DEFAULT_OPENID = ByteString.EMPTY;
  public static final ByteString DEFAULT_MCODE = ByteString.EMPTY;
  public static final Integer DEFAULT_GAMELEVEL = 0;
  public static final Integer DEFAULT_OP_TYPE = 0;
  public static final Integer DEFAULT_SOURCEID = 0;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString userid;

  /**
   * QQ号
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString roomid;

  /**
   *
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString nick_name;

  /**
   * 用户昵称
   */
  @ProtoField(tag = 4, type = BYTES)
  public final ByteString chat_msg;

  /**
   * 文字消息（ChatMsg序列化后的数据）
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString openid;

  /**
   * openid
   */
  @ProtoField(tag = 6, type = BYTES)
  public final ByteString mcode;

  @ProtoField(tag = 7, type = UINT32)
  public final Integer gamelevel;

  @ProtoField(tag = 8, type = INT32)
  public final Integer op_type;

  /**
   * 运营类型，详见enum ChatOperationType
   */
  @ProtoField(tag = 9, type = INT32)
  public final Integer sourceid;

  public RoomChatReq(ByteString userid, ByteString roomid, ByteString nick_name, ByteString chat_msg, ByteString openid, ByteString mcode, Integer gamelevel, Integer op_type, Integer sourceid) {
    this.userid = userid;
    this.roomid = roomid;
    this.nick_name = nick_name;
    this.chat_msg = chat_msg;
    this.openid = openid;
    this.mcode = mcode;
    this.gamelevel = gamelevel;
    this.op_type = op_type;
    this.sourceid = sourceid;
  }

  private RoomChatReq(Builder builder) {
    this(builder.userid, builder.roomid, builder.nick_name, builder.chat_msg, builder.openid, builder.mcode, builder.gamelevel, builder.op_type, builder.sourceid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RoomChatReq)) return false;
    RoomChatReq o = (RoomChatReq) other;
    return equals(userid, o.userid)
        && equals(roomid, o.roomid)
        && equals(nick_name, o.nick_name)
        && equals(chat_msg, o.chat_msg)
        && equals(openid, o.openid)
        && equals(mcode, o.mcode)
        && equals(gamelevel, o.gamelevel)
        && equals(op_type, o.op_type)
        && equals(sourceid, o.sourceid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userid != null ? userid.hashCode() : 0;
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      result = result * 37 + (nick_name != null ? nick_name.hashCode() : 0);
      result = result * 37 + (chat_msg != null ? chat_msg.hashCode() : 0);
      result = result * 37 + (openid != null ? openid.hashCode() : 0);
      result = result * 37 + (mcode != null ? mcode.hashCode() : 0);
      result = result * 37 + (gamelevel != null ? gamelevel.hashCode() : 0);
      result = result * 37 + (op_type != null ? op_type.hashCode() : 0);
      result = result * 37 + (sourceid != null ? sourceid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RoomChatReq> {

    public ByteString userid;
    public ByteString roomid;
    public ByteString nick_name;
    public ByteString chat_msg;
    public ByteString openid;
    public ByteString mcode;
    public Integer gamelevel;
    public Integer op_type;
    public Integer sourceid;

    public Builder() {
    }

    public Builder(RoomChatReq message) {
      super(message);
      if (message == null) return;
      this.userid = message.userid;
      this.roomid = message.roomid;
      this.nick_name = message.nick_name;
      this.chat_msg = message.chat_msg;
      this.openid = message.openid;
      this.mcode = message.mcode;
      this.gamelevel = message.gamelevel;
      this.op_type = message.op_type;
      this.sourceid = message.sourceid;
    }

    public Builder userid(ByteString userid) {
      this.userid = userid;
      return this;
    }

    /**
     * QQ号
     */
    public Builder roomid(ByteString roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     *
     */
    public Builder nick_name(ByteString nick_name) {
      this.nick_name = nick_name;
      return this;
    }

    /**
     * 用户昵称
     */
    public Builder chat_msg(ByteString chat_msg) {
      this.chat_msg = chat_msg;
      return this;
    }

    /**
     * 文字消息（ChatMsg序列化后的数据）
     */
    public Builder openid(ByteString openid) {
      this.openid = openid;
      return this;
    }

    /**
     * openid
     */
    public Builder mcode(ByteString mcode) {
      this.mcode = mcode;
      return this;
    }

    public Builder gamelevel(Integer gamelevel) {
      this.gamelevel = gamelevel;
      return this;
    }

    public Builder op_type(Integer op_type) {
      this.op_type = op_type;
      return this;
    }

    /**
     * 运营类型，详见enum ChatOperationType
     */
    public Builder sourceid(Integer sourceid) {
      this.sourceid = sourceid;
      return this;
    }

    @Override
    public RoomChatReq build() {
      checkRequiredFields();
      return new RoomChatReq(this);
    }
  }
}
