// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\auth.proto
package com.tencent.protocol.tga.auth;

import com.squareup.tga.ProtoEnum;

public enum auth_cmd_types
    implements ProtoEnum {
  CMD_AUTH(4102);

  private final int value;

  private auth_cmd_types(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
