// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\match_subscribe.proto
package com.tencent.protocol.tga.matchsubscribe;

import com.squareup.tga.ProtoEnum;

public enum CMD
    implements ProtoEnum {
  CMD_MATCH(4117);

  private final int value;

  private CMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
