// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\match_subscribe.proto
package com.tencent.protocol.tga.matchsubscribe;

import com.squareup.tga.ProtoEnum;

public enum SUBCMD
    implements ProtoEnum {
  SUBCMD_SUBSCRIBE_MATCH_OP(3);

  private final int value;

  private SUBCMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
