// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\match_subscribe.proto
package com.tencent.protocol.tga.matchsubscribe;

import com.squareup.tga.ProtoEnum;

public enum SubscribeOperationType
    implements ProtoEnum {
  SUB_OP_TYPE_SUBSCRIBE(1),
  /**
   * 订阅
   */
  SUB_OP_TYPE_CANCEL(2);

  private final int value;

  private SubscribeOperationType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
