// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\online_data.proto
package com.tencent.protocol.tga.online_data;

import com.squareup.tga.ProtoEnum;

public enum CMD
    implements ProtoEnum {
  CMD_ONLINE_DATA(4147);

  private final int value;

  private CMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
