// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\online_data.proto
package com.tencent.protocol.tga.online_data;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class OnlineHelloRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final ByteString DEFAULT_ERR_MSG = ByteString.EMPTY;
  public static final Integer DEFAULT_HELLO_TIMESPAN = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString err_msg;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer hello_timespan;

  public OnlineHelloRsp(Integer result, ByteString err_msg, Integer hello_timespan) {
    this.result = result;
    this.err_msg = err_msg;
    this.hello_timespan = hello_timespan;
  }

  private OnlineHelloRsp(Builder builder) {
    this(builder.result, builder.err_msg, builder.hello_timespan);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OnlineHelloRsp)) return false;
    OnlineHelloRsp o = (OnlineHelloRsp) other;
    return equals(result, o.result)
        && equals(err_msg, o.err_msg)
        && equals(hello_timespan, o.hello_timespan);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (err_msg != null ? err_msg.hashCode() : 0);
      result = result * 37 + (hello_timespan != null ? hello_timespan.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<OnlineHelloRsp> {

    public Integer result;
    public ByteString err_msg;
    public Integer hello_timespan;

    public Builder() {
    }

    public Builder(OnlineHelloRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.err_msg = message.err_msg;
      this.hello_timespan = message.hello_timespan;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    public Builder err_msg(ByteString err_msg) {
      this.err_msg = err_msg;
      return this;
    }

    public Builder hello_timespan(Integer hello_timespan) {
      this.hello_timespan = hello_timespan;
      return this;
    }

    @Override
    public OnlineHelloRsp build() {
      checkRequiredFields();
      return new OnlineHelloRsp(this);
    }
  }
}
