// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\ppkdc_schedule.proto
package com.tencent.protocol.tga.ppkdc_schedule;

import com.squareup.tga.ProtoEnum;

public enum CMD
    implements ProtoEnum {
  CMD_PPKDC_SCHEDULE(4162);

  private final int value;

  private CMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
