// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\ppkdc_schedule.proto
package com.tencent.protocol.tga.ppkdc_schedule;

import com.squareup.tga.ProtoEnum;

public enum MatchState
    implements ProtoEnum {
  E_MATCH_STATE_NOT_START(1),
  /**
   * 赛事未开始
   */
  E_MATCH_STATE_CANCELED(2),
  /**
   * 赛事已取消
   */
  E_MATCH_STATE_RUNNING(3),
  /**
   * 赛事进行中
   */
  E_MATCH_STATE_FINISHED(4);

  private final int value;

  private MatchState(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
