// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\ppkdc_schedule.proto
package com.tencent.protocol.tga.ppkdc_schedule;

import com.squareup.tga.ProtoEnum;

public enum SUBCMD
    implements ProtoEnum {
  SUBCMD_GET_CHANNEL_LIST(1);

  private final int value;

  private SUBCMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
