// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat_msg.proto
package com.tencent.protocol.tga.chatMsg;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import java.util.Collections;
import java.util.List;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REPEATED;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * 包厢成员列表和邀请信息列表
 */
public final class BalconyMemberNotify extends Message {

  public static final ByteString DEFAULT_BALCONY_ID = ByteString.EMPTY;
  public static final List<TVUserInfo> DEFAULT_USER_LIST = Collections.emptyList();
  public static final Integer DEFAULT_TIPS_TYPE = 0;
  public static final ByteString DEFAULT_TIPS = ByteString.EMPTY;
  public static final ByteString DEFAULT_ENTER_ID = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString balcony_id;

  /**
   * 包厢id
   */
  @ProtoField(tag = 2, label = REPEATED, messageType = TVUserInfo.class)
  public final List<TVUserInfo> user_list;

  /**
   * 在线成员id列表
   */
  @ProtoField(tag = 3, type = UINT32)
  public final Integer tips_type;

  /**
   * tips类型,参见BalconyTipsType
   */
  @ProtoField(tag = 4, type = BYTES)
  public final ByteString tips;

  /**
   * tips内容
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString enter_id;

  public BalconyMemberNotify(ByteString balcony_id, List<TVUserInfo> user_list, Integer tips_type, ByteString tips, ByteString enter_id) {
    this.balcony_id = balcony_id;
    this.user_list = immutableCopyOf(user_list);
    this.tips_type = tips_type;
    this.tips = tips;
    this.enter_id = enter_id;
  }

  private BalconyMemberNotify(Builder builder) {
    this(builder.balcony_id, builder.user_list, builder.tips_type, builder.tips, builder.enter_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BalconyMemberNotify)) return false;
    BalconyMemberNotify o = (BalconyMemberNotify) other;
    return equals(balcony_id, o.balcony_id)
        && equals(user_list, o.user_list)
        && equals(tips_type, o.tips_type)
        && equals(tips, o.tips)
        && equals(enter_id, o.enter_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = balcony_id != null ? balcony_id.hashCode() : 0;
      result = result * 37 + (user_list != null ? user_list.hashCode() : 1);
      result = result * 37 + (tips_type != null ? tips_type.hashCode() : 0);
      result = result * 37 + (tips != null ? tips.hashCode() : 0);
      result = result * 37 + (enter_id != null ? enter_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BalconyMemberNotify> {

    public ByteString balcony_id;
    public List<TVUserInfo> user_list;
    public Integer tips_type;
    public ByteString tips;
    public ByteString enter_id;

    public Builder() {
    }

    public Builder(BalconyMemberNotify message) {
      super(message);
      if (message == null) return;
      this.balcony_id = message.balcony_id;
      this.user_list = copyOf(message.user_list);
      this.tips_type = message.tips_type;
      this.tips = message.tips;
      this.enter_id = message.enter_id;
    }

    public Builder balcony_id(ByteString balcony_id) {
      this.balcony_id = balcony_id;
      return this;
    }

    /**
     * 包厢id
     */
    public Builder user_list(List<TVUserInfo> user_list) {
      this.user_list = checkForNulls(user_list);
      return this;
    }

    /**
     * 在线成员id列表
     */
    public Builder tips_type(Integer tips_type) {
      this.tips_type = tips_type;
      return this;
    }

    /**
     * tips类型,参见BalconyTipsType
     */
    public Builder tips(ByteString tips) {
      this.tips = tips;
      return this;
    }

    /**
     * tips内容
     */
    public Builder enter_id(ByteString enter_id) {
      this.enter_id = enter_id;
      return this;
    }

    @Override
    public BalconyMemberNotify build() {
      checkRequiredFields();
      return new BalconyMemberNotify(this);
    }
  }
}
