// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat_msg.proto
package com.tencent.protocol.tga.chatMsg;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;

import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * sdk多赛事直播下线通知
 */
public final class SDKNotifyLiveOffline extends Message {

  public static final Integer DEFAULT_SOURCE_ID = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer source_id;

  public SDKNotifyLiveOffline(Integer source_id) {
    this.source_id = source_id;
  }

  private SDKNotifyLiveOffline(Builder builder) {
    this(builder.source_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SDKNotifyLiveOffline)) return false;
    return equals(source_id, ((SDKNotifyLiveOffline) other).source_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = source_id != null ? source_id.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<SDKNotifyLiveOffline> {

    public Integer source_id;

    public Builder() {
    }

    public Builder(SDKNotifyLiveOffline message) {
      super(message);
      if (message == null) return;
      this.source_id = message.source_id;
    }

    public Builder source_id(Integer source_id) {
      this.source_id = source_id;
      return this;
    }

    @Override
    public SDKNotifyLiveOffline build() {
      checkRequiredFields();
      return new SDKNotifyLiveOffline(this);
    }
  }
}
