// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\chat_msg.proto
package com.tencent.protocol.tga.chatMsg;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * SDK游戏玩家邀请游戏好友参与对战
 */
public final class SDKPlayerInviteFriendFightMsg extends Message {

  public static final ByteString DEFAULT_USER_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_USER_NAME = ByteString.EMPTY;
  public static final ByteString DEFAULT_FRIEND_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_FRIEND_NAME = ByteString.EMPTY;
  public static final ByteString DEFAULT_GAME_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_ROOM_ID = ByteString.EMPTY;
  public static final Integer DEFAULT_SEQ = 0;
  public static final ByteString DEFAULT_BATTLE_MODE = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString user_id;

  /**
   * 玩家id
   */
  @ProtoField(tag = 2, type = BYTES, label = REQUIRED)
  public final ByteString user_name;

  /**
   * 玩家名称
   */
  @ProtoField(tag = 3, type = BYTES, label = REQUIRED)
  public final ByteString friend_id;

  /**
   * 好友id
   */
  @ProtoField(tag = 4, type = BYTES, label = REQUIRED)
  public final ByteString friend_name;

  /**
   * 好友名称
   */
  @ProtoField(tag = 5, type = BYTES, label = REQUIRED)
  public final ByteString game_id;

  /**
   * 游戏id
   */
  @ProtoField(tag = 6, type = BYTES)
  public final ByteString room_id;

  /**
   * 房间id
   */
  @ProtoField(tag = 7, type = UINT32)
  public final Integer seq;

  /**
   * 消息序列号，唯一标识一条消息，可以用来去重
   */
  @ProtoField(tag = 8, type = BYTES)
  public final ByteString battle_mode;

  public SDKPlayerInviteFriendFightMsg(ByteString user_id, ByteString user_name, ByteString friend_id, ByteString friend_name, ByteString game_id, ByteString room_id, Integer seq, ByteString battle_mode) {
    this.user_id = user_id;
    this.user_name = user_name;
    this.friend_id = friend_id;
    this.friend_name = friend_name;
    this.game_id = game_id;
    this.room_id = room_id;
    this.seq = seq;
    this.battle_mode = battle_mode;
  }

  private SDKPlayerInviteFriendFightMsg(Builder builder) {
    this(builder.user_id, builder.user_name, builder.friend_id, builder.friend_name, builder.game_id, builder.room_id, builder.seq, builder.battle_mode);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SDKPlayerInviteFriendFightMsg)) return false;
    SDKPlayerInviteFriendFightMsg o = (SDKPlayerInviteFriendFightMsg) other;
    return equals(user_id, o.user_id)
        && equals(user_name, o.user_name)
        && equals(friend_id, o.friend_id)
        && equals(friend_name, o.friend_name)
        && equals(game_id, o.game_id)
        && equals(room_id, o.room_id)
        && equals(seq, o.seq)
        && equals(battle_mode, o.battle_mode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = user_id != null ? user_id.hashCode() : 0;
      result = result * 37 + (user_name != null ? user_name.hashCode() : 0);
      result = result * 37 + (friend_id != null ? friend_id.hashCode() : 0);
      result = result * 37 + (friend_name != null ? friend_name.hashCode() : 0);
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (room_id != null ? room_id.hashCode() : 0);
      result = result * 37 + (seq != null ? seq.hashCode() : 0);
      result = result * 37 + (battle_mode != null ? battle_mode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SDKPlayerInviteFriendFightMsg> {

    public ByteString user_id;
    public ByteString user_name;
    public ByteString friend_id;
    public ByteString friend_name;
    public ByteString game_id;
    public ByteString room_id;
    public Integer seq;
    public ByteString battle_mode;

    public Builder() {
    }

    public Builder(SDKPlayerInviteFriendFightMsg message) {
      super(message);
      if (message == null) return;
      this.user_id = message.user_id;
      this.user_name = message.user_name;
      this.friend_id = message.friend_id;
      this.friend_name = message.friend_name;
      this.game_id = message.game_id;
      this.room_id = message.room_id;
      this.seq = message.seq;
      this.battle_mode = message.battle_mode;
    }

    public Builder user_id(ByteString user_id) {
      this.user_id = user_id;
      return this;
    }

    /**
     * 玩家id
     */
    public Builder user_name(ByteString user_name) {
      this.user_name = user_name;
      return this;
    }

    /**
     * 玩家名称
     */
    public Builder friend_id(ByteString friend_id) {
      this.friend_id = friend_id;
      return this;
    }

    /**
     * 好友id
     */
    public Builder friend_name(ByteString friend_name) {
      this.friend_name = friend_name;
      return this;
    }

    /**
     * 好友名称
     */
    public Builder game_id(ByteString game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏id
     */
    public Builder room_id(ByteString room_id) {
      this.room_id = room_id;
      return this;
    }

    /**
     * 房间id
     */
    public Builder seq(Integer seq) {
      this.seq = seq;
      return this;
    }

    /**
     * 消息序列号，唯一标识一条消息，可以用来去重
     */
    public Builder battle_mode(ByteString battle_mode) {
      this.battle_mode = battle_mode;
      return this;
    }

    @Override
    public SDKPlayerInviteFriendFightMsg build() {
      checkRequiredFields();
      return new SDKPlayerInviteFriendFightMsg(this);
    }
  }
}
