// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\tv_user_info.proto
package com.tencent.protocol.tga.chatMsg;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * 用户资料
 */
public final class TVUserInfo extends Message {

  public static final ByteString DEFAULT_USER_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_NICK = ByteString.EMPTY;
  public static final ByteString DEFAULT_FACE_URL = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString user_id;

  /**
   * 用户id
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString nick;

  /**
   * 昵称
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString face_url;

  public TVUserInfo(ByteString user_id, ByteString nick, ByteString face_url) {
    this.user_id = user_id;
    this.nick = nick;
    this.face_url = face_url;
  }

  private TVUserInfo(Builder builder) {
    this(builder.user_id, builder.nick, builder.face_url);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TVUserInfo)) return false;
    TVUserInfo o = (TVUserInfo) other;
    return equals(user_id, o.user_id)
        && equals(nick, o.nick)
        && equals(face_url, o.face_url);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = user_id != null ? user_id.hashCode() : 0;
      result = result * 37 + (nick != null ? nick.hashCode() : 0);
      result = result * 37 + (face_url != null ? face_url.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TVUserInfo> {

    public ByteString user_id;
    public ByteString nick;
    public ByteString face_url;

    public Builder() {
    }

    public Builder(TVUserInfo message) {
      super(message);
      if (message == null) return;
      this.user_id = message.user_id;
      this.nick = message.nick;
      this.face_url = message.face_url;
    }

    public Builder user_id(ByteString user_id) {
      this.user_id = user_id;
      return this;
    }

    /**
     * 用户id
     */
    public Builder nick(ByteString nick) {
      this.nick = nick;
      return this;
    }

    /**
     * 昵称
     */
    public Builder face_url(ByteString face_url) {
      this.face_url = face_url;
      return this;
    }

    @Override
    public TVUserInfo build() {
      checkRequiredFields();
      return new TVUserInfo(this);
    }
  }
}
