// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\hpjy_treasure.proto
package com.tencent.protocol.tga.hpjy_treasure;

import com.squareup.tga.ProtoEnum;

public enum CMD
    implements ProtoEnum {
  CMD_HPJY_TREASURE(4168);

  private final int value;

  private CMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
