// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\hpjy_treasure.proto
package com.tencent.protocol.tga.hpjy_treasure;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import java.util.Collections;
import java.util.List;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REPEATED;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class ReceiveTreasureBoxRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final ByteString DEFAULT_ERR_INFO = ByteString.EMPTY;
  public static final ByteString DEFAULT_BOXID = ByteString.EMPTY;
  public static final List<ReceiveItem> DEFAULT_RECV_BOX = Collections.emptyList();

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  /**
   * 开宝箱结果
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString err_info;

  /**
   * 错误信息
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString boxid;

  @ProtoField(tag = 4, label = REPEATED, messageType = ReceiveItem.class)
  public final List<ReceiveItem> recv_box;

  public ReceiveTreasureBoxRsp(Integer result, ByteString err_info, ByteString boxid, List<ReceiveItem> recv_box) {
    this.result = result;
    this.err_info = err_info;
    this.boxid = boxid;
    this.recv_box = immutableCopyOf(recv_box);
  }

  private ReceiveTreasureBoxRsp(Builder builder) {
    this(builder.result, builder.err_info, builder.boxid, builder.recv_box);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReceiveTreasureBoxRsp)) return false;
    ReceiveTreasureBoxRsp o = (ReceiveTreasureBoxRsp) other;
    return equals(result, o.result)
        && equals(err_info, o.err_info)
        && equals(boxid, o.boxid)
        && equals(recv_box, o.recv_box);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (err_info != null ? err_info.hashCode() : 0);
      result = result * 37 + (boxid != null ? boxid.hashCode() : 0);
      result = result * 37 + (recv_box != null ? recv_box.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReceiveTreasureBoxRsp> {

    public Integer result;
    public ByteString err_info;
    public ByteString boxid;
    public List<ReceiveItem> recv_box;

    public Builder() {
    }

    public Builder(ReceiveTreasureBoxRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.err_info = message.err_info;
      this.boxid = message.boxid;
      this.recv_box = copyOf(message.recv_box);
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 开宝箱结果
     */
    public Builder err_info(ByteString err_info) {
      this.err_info = err_info;
      return this;
    }

    /**
     * 错误信息
     */
    public Builder boxid(ByteString boxid) {
      this.boxid = boxid;
      return this;
    }

    public Builder recv_box(List<ReceiveItem> recv_box) {
      this.recv_box = checkForNulls(recv_box);
      return this;
    }

    @Override
    public ReceiveTreasureBoxRsp build() {
      checkRequiredFields();
      return new ReceiveTreasureBoxRsp(this);
    }
  }
}
