// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\hpjy_treasure.proto
package com.tencent.protocol.tga.hpjy_treasure;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * /////////////////////////////////////////////////////////////
 * SUBCMD_RECEIVE_TREASURE_BOX         = 0x01; // 领取宝箱
 */
public final class ReceiveTreasureBoxReq extends Message {

  public static final ByteString DEFAULT_USER_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_BOXID = ByteString.EMPTY;
  public static final Integer DEFAULT_SERVER_TIME = 0;
  public static final ByteString DEFAULT_TIME_STAMP = ByteString.EMPTY;
  public static final ByteString DEFAULT_RANDOM_VALUE = ByteString.EMPTY;
  public static final ByteString DEFAULT_USER_NAME = ByteString.EMPTY;
  public static final Integer DEFAULT_LEVEL = 0;
  public static final Integer DEFAULT_CLIENT_TYPE = 0;
  public static final Integer DEFAULT_AREA = 0;
  public static final ByteString DEFAULT_OPENID = ByteString.EMPTY;
  public static final Integer DEFAULT_PLATID = 0;
  public static final Integer DEFAULT_AREAID = 0;
  public static final ByteString DEFAULT_MCODE = ByteString.EMPTY;
  public static final Integer DEFAULT_IS_H5 = 0;
  public static final Integer DEFAULT_CLIENTIP = 0;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString user_id;

  /**
   * 用户id
   */
  @ProtoField(tag = 2, type = BYTES, label = REQUIRED)
  public final ByteString boxid;

  /**
   * 宝箱id
   */
  @ProtoField(tag = 3, type = UINT32, label = REQUIRED)
  public final Integer server_time;

  /**
   * 服务器时间,拉取宝箱列表时获取
   */
  @ProtoField(tag = 4, type = BYTES)
  public final ByteString time_stamp;

  /**
   * 时间戳-单位秒
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString random_value;

  /**
   * 随机数
   */
  @ProtoField(tag = 6, type = BYTES)
  public final ByteString user_name;

  @ProtoField(tag = 7, type = UINT32)
  public final Integer level;

  @ProtoField(tag = 8, type = UINT32)
  public final Integer client_type;

  @ProtoField(tag = 9, type = UINT32)
  public final Integer area;

  /**
   * 服务器：微信（1），手Q（2）
   */
  @ProtoField(tag = 10, type = BYTES)
  public final ByteString openid;

  /**
   * 注意，这里是game_openid
   */
  @ProtoField(tag = 11, type = UINT32)
  public final Integer platid;

  /**
   * 平台：IOS（0），安卓（1）
   */
  @ProtoField(tag = 12, type = UINT32)
  public final Integer areaid;

  /**
   *
   */
  @ProtoField(tag = 13, type = BYTES)
  public final ByteString mcode;

  @ProtoField(tag = 14, type = UINT32)
  public final Integer is_h5;

  /**
   * 是否来自h5
   */
  @ProtoField(tag = 15, type = UINT32)
  public final Integer clientip;

  public ReceiveTreasureBoxReq(ByteString user_id, ByteString boxid, Integer server_time, ByteString time_stamp, ByteString random_value, ByteString user_name, Integer level, Integer client_type, Integer area, ByteString openid, Integer platid, Integer areaid, ByteString mcode, Integer is_h5, Integer clientip) {
    this.user_id = user_id;
    this.boxid = boxid;
    this.server_time = server_time;
    this.time_stamp = time_stamp;
    this.random_value = random_value;
    this.user_name = user_name;
    this.level = level;
    this.client_type = client_type;
    this.area = area;
    this.openid = openid;
    this.platid = platid;
    this.areaid = areaid;
    this.mcode = mcode;
    this.is_h5 = is_h5;
    this.clientip = clientip;
  }

  private ReceiveTreasureBoxReq(Builder builder) {
    this(builder.user_id, builder.boxid, builder.server_time, builder.time_stamp, builder.random_value, builder.user_name, builder.level, builder.client_type, builder.area, builder.openid, builder.platid, builder.areaid, builder.mcode, builder.is_h5, builder.clientip);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReceiveTreasureBoxReq)) return false;
    ReceiveTreasureBoxReq o = (ReceiveTreasureBoxReq) other;
    return equals(user_id, o.user_id)
        && equals(boxid, o.boxid)
        && equals(server_time, o.server_time)
        && equals(time_stamp, o.time_stamp)
        && equals(random_value, o.random_value)
        && equals(user_name, o.user_name)
        && equals(level, o.level)
        && equals(client_type, o.client_type)
        && equals(area, o.area)
        && equals(openid, o.openid)
        && equals(platid, o.platid)
        && equals(areaid, o.areaid)
        && equals(mcode, o.mcode)
        && equals(is_h5, o.is_h5)
        && equals(clientip, o.clientip);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = user_id != null ? user_id.hashCode() : 0;
      result = result * 37 + (boxid != null ? boxid.hashCode() : 0);
      result = result * 37 + (server_time != null ? server_time.hashCode() : 0);
      result = result * 37 + (time_stamp != null ? time_stamp.hashCode() : 0);
      result = result * 37 + (random_value != null ? random_value.hashCode() : 0);
      result = result * 37 + (user_name != null ? user_name.hashCode() : 0);
      result = result * 37 + (level != null ? level.hashCode() : 0);
      result = result * 37 + (client_type != null ? client_type.hashCode() : 0);
      result = result * 37 + (area != null ? area.hashCode() : 0);
      result = result * 37 + (openid != null ? openid.hashCode() : 0);
      result = result * 37 + (platid != null ? platid.hashCode() : 0);
      result = result * 37 + (areaid != null ? areaid.hashCode() : 0);
      result = result * 37 + (mcode != null ? mcode.hashCode() : 0);
      result = result * 37 + (is_h5 != null ? is_h5.hashCode() : 0);
      result = result * 37 + (clientip != null ? clientip.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ReceiveTreasureBoxReq> {

    public ByteString user_id;
    public ByteString boxid;
    public Integer server_time;
    public ByteString time_stamp;
    public ByteString random_value;
    public ByteString user_name;
    public Integer level;
    public Integer client_type;
    public Integer area;
    public ByteString openid;
    public Integer platid;
    public Integer areaid;
    public ByteString mcode;
    public Integer is_h5;
    public Integer clientip;

    public Builder() {
    }

    public Builder(ReceiveTreasureBoxReq message) {
      super(message);
      if (message == null) return;
      this.user_id = message.user_id;
      this.boxid = message.boxid;
      this.server_time = message.server_time;
      this.time_stamp = message.time_stamp;
      this.random_value = message.random_value;
      this.user_name = message.user_name;
      this.level = message.level;
      this.client_type = message.client_type;
      this.area = message.area;
      this.openid = message.openid;
      this.platid = message.platid;
      this.areaid = message.areaid;
      this.mcode = message.mcode;
      this.is_h5 = message.is_h5;
      this.clientip = message.clientip;
    }

    public Builder user_id(ByteString user_id) {
      this.user_id = user_id;
      return this;
    }

    /**
     * 用户id
     */
    public Builder boxid(ByteString boxid) {
      this.boxid = boxid;
      return this;
    }

    /**
     * 宝箱id
     */
    public Builder server_time(Integer server_time) {
      this.server_time = server_time;
      return this;
    }

    /**
     * 服务器时间,拉取宝箱列表时获取
     */
    public Builder time_stamp(ByteString time_stamp) {
      this.time_stamp = time_stamp;
      return this;
    }

    /**
     * 时间戳-单位秒
     */
    public Builder random_value(ByteString random_value) {
      this.random_value = random_value;
      return this;
    }

    /**
     * 随机数
     */
    public Builder user_name(ByteString user_name) {
      this.user_name = user_name;
      return this;
    }

    public Builder level(Integer level) {
      this.level = level;
      return this;
    }

    public Builder client_type(Integer client_type) {
      this.client_type = client_type;
      return this;
    }

    public Builder area(Integer area) {
      this.area = area;
      return this;
    }

    /**
     * 服务器：微信（1），手Q（2）
     */
    public Builder openid(ByteString openid) {
      this.openid = openid;
      return this;
    }

    /**
     * 注意，这里是game_openid
     */
    public Builder platid(Integer platid) {
      this.platid = platid;
      return this;
    }

    /**
     * 平台：IOS（0），安卓（1）
     */
    public Builder areaid(Integer areaid) {
      this.areaid = areaid;
      return this;
    }

    /**
     *
     */
    public Builder mcode(ByteString mcode) {
      this.mcode = mcode;
      return this;
    }

    public Builder is_h5(Integer is_h5) {
      this.is_h5 = is_h5;
      return this;
    }

    /**
     * 是否来自h5
     */
    public Builder clientip(Integer clientip) {
      this.clientip = clientip;
      return this;
    }

    @Override
    public ReceiveTreasureBoxReq build() {
      checkRequiredFields();
      return new ReceiveTreasureBoxReq(this);
    }
  }
}
