// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\hpjy_treasure.proto
package com.tencent.protocol.tga.hpjy_treasure;

import com.squareup.tga.ProtoEnum;

public enum SUBCMD
    implements ProtoEnum {
  SUBCMD_RECEIVE_TREASURE_BOX(1);

  private final int value;

  private SUBCMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
