// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\room_usernum_notify.proto
package com.tencent.protocol.tga.room_usernum_notify;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class RoomUsernumNotify extends Message {

  public static final ByteString DEFAULT_ROOMID = ByteString.EMPTY;
  public static final Integer DEFAULT_USER_NUM = 0;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString roomid;

  /**
   * ����ID
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer user_num;

  public RoomUsernumNotify(ByteString roomid, Integer user_num) {
    this.roomid = roomid;
    this.user_num = user_num;
  }

  private RoomUsernumNotify(Builder builder) {
    this(builder.roomid, builder.user_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RoomUsernumNotify)) return false;
    RoomUsernumNotify o = (RoomUsernumNotify) other;
    return equals(roomid, o.roomid)
        && equals(user_num, o.user_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (user_num != null ? user_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RoomUsernumNotify> {

    public ByteString roomid;
    public Integer user_num;

    public Builder() {
    }

    public Builder(RoomUsernumNotify message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.user_num = message.user_num;
    }

    public Builder roomid(ByteString roomid) {
      this.roomid = roomid;
      return this;
    }

    /**
     * ����ID
     */
    public Builder user_num(Integer user_num) {
      this.user_num = user_num;
      return this;
    }

    @Override
    public RoomUsernumNotify build() {
      checkRequiredFields();
      return new RoomUsernumNotify(this);
    }
  }
}
