// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.ProtoEnum;

public enum AccountType
    implements ProtoEnum {
  AccountType_QQ(1),
  /**
   * QQ号
   */
  AccountType_WeChat(2),
  /**
   * 微信号
   */
  AccountType_Tourist(3),
  /**
   * 游客
   */
  AccountType_LiveToken(4);

  private final int value;

  private AccountType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
