// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;

public final class ArticleItem extends Message {

  public static final ByteString DEFAULT_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_TITLE = ByteString.EMPTY;
  public static final ByteString DEFAULT_COVER_IMAGE = ByteString.EMPTY;
  public static final ByteString DEFAULT_AUTHOR = ByteString.EMPTY;
  public static final ByteString DEFAULT_DESCRIPTION = ByteString.EMPTY;
  public static final ByteString DEFAULT_URL = ByteString.EMPTY;
  public static final Integer DEFAULT_CREATE_TIME = 0;
  public static final ByteString DEFAULT_GAME_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_CID = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString id;

  /**
   * 文章ID
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString title;

  /**
   * 标题
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString cover_image;

  /**
   * 封面
   */
  @ProtoField(tag = 4, type = BYTES)
  public final ByteString author;

  /**
   * 作者
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString description;

  /**
   * 描述
   */
  @ProtoField(tag = 6, type = BYTES)
  public final ByteString url;

  /**
   * 文章H5地址
   */
  @ProtoField(tag = 7, type = UINT32)
  public final Integer create_time;

  /**
   * 创建时间
   */
  @ProtoField(tag = 8, type = BYTES)
  public final ByteString game_id;

  /**
   * 游戏ID
   */
  @ProtoField(tag = 9, type = BYTES)
  public final ByteString cid;

  public ArticleItem(ByteString id, ByteString title, ByteString cover_image, ByteString author, ByteString description, ByteString url, Integer create_time, ByteString game_id, ByteString cid) {
    this.id = id;
    this.title = title;
    this.cover_image = cover_image;
    this.author = author;
    this.description = description;
    this.url = url;
    this.create_time = create_time;
    this.game_id = game_id;
    this.cid = cid;
  }

  private ArticleItem(Builder builder) {
    this(builder.id, builder.title, builder.cover_image, builder.author, builder.description, builder.url, builder.create_time, builder.game_id, builder.cid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ArticleItem)) return false;
    ArticleItem o = (ArticleItem) other;
    return equals(id, o.id)
        && equals(title, o.title)
        && equals(cover_image, o.cover_image)
        && equals(author, o.author)
        && equals(description, o.description)
        && equals(url, o.url)
        && equals(create_time, o.create_time)
        && equals(game_id, o.game_id)
        && equals(cid, o.cid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = id != null ? id.hashCode() : 0;
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (cover_image != null ? cover_image.hashCode() : 0);
      result = result * 37 + (author != null ? author.hashCode() : 0);
      result = result * 37 + (description != null ? description.hashCode() : 0);
      result = result * 37 + (url != null ? url.hashCode() : 0);
      result = result * 37 + (create_time != null ? create_time.hashCode() : 0);
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (cid != null ? cid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ArticleItem> {

    public ByteString id;
    public ByteString title;
    public ByteString cover_image;
    public ByteString author;
    public ByteString description;
    public ByteString url;
    public Integer create_time;
    public ByteString game_id;
    public ByteString cid;

    public Builder() {
    }

    public Builder(ArticleItem message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
      this.title = message.title;
      this.cover_image = message.cover_image;
      this.author = message.author;
      this.description = message.description;
      this.url = message.url;
      this.create_time = message.create_time;
      this.game_id = message.game_id;
      this.cid = message.cid;
    }

    public Builder id(ByteString id) {
      this.id = id;
      return this;
    }

    /**
     * 文章ID
     */
    public Builder title(ByteString title) {
      this.title = title;
      return this;
    }

    /**
     * 标题
     */
    public Builder cover_image(ByteString cover_image) {
      this.cover_image = cover_image;
      return this;
    }

    /**
     * 封面
     */
    public Builder author(ByteString author) {
      this.author = author;
      return this;
    }

    /**
     * 作者
     */
    public Builder description(ByteString description) {
      this.description = description;
      return this;
    }

    /**
     * 描述
     */
    public Builder url(ByteString url) {
      this.url = url;
      return this;
    }

    /**
     * 文章H5地址
     */
    public Builder create_time(Integer create_time) {
      this.create_time = create_time;
      return this;
    }

    /**
     * 创建时间
     */
    public Builder game_id(ByteString game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏ID
     */
    public Builder cid(ByteString cid) {
      this.cid = cid;
      return this;
    }

    @Override
    public ArticleItem build() {
      return new ArticleItem(this);
    }
  }
}
