// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.ProtoEnum;

public enum ClientType
    implements ProtoEnum {
  EZTV_APP_ANDROID(1),
  /**
   * 鹅掌APP 安卓
   */
  EZTV_APP_IOS(2),
  /**
   * 鹅掌APP 苹果
   */
  EZTV_TOOL_ANDROID(3),
  /**
   * 鹅掌直播助手 安卓
   */
  EZTV_TOOL_IOS(4),
  /**
   * 鹅掌直播助手 苹果
   */
  EZTV_TOOL_OBS(5),
  /**
   * 鹅掌直播助手 OBS
   */
  SDK_WZRY_ANDROID(6),
  /**
   * sdk插件王者荣耀-安卓
   */
  SDK_WZRY_IOS(7),
  /**
   * sdk插件王者荣耀-苹果
   */
  SDK_FC_ANDROID(8),
  /**
   * sdk插件飞车-安卓
   */
  SDK_FC_IOS(9),
  /**
   * sdk插件飞车-iOS
   */
  SDK_SMOBA_HELPER_ANDROID(10),
  /**
   * sdk插件王者荣耀助手-安卓
   */
  SDK_SMOBA_HELPER_IOS(11),
  /**
   * sdk插件王者荣耀助手-iOS
   */
  SDK_FC_H5_ANDORID(12),
  /**
   * 飞车安卓-H5直播页面
   */
  SDK_FC_H5_IOS(13),
  /**
   * 飞车IOS-H5直播页面
   */
  SDK_WZRY_H5_ANDROID(14),
  /**
   * 王者赛事页-安卓
   */
  SDK_WZRY_H5_IOS(15),
  /**
   * 王者赛事页-IOS
   */
  SDK_HLDDZ_ANDROID(16),
  /**
   * 欢乐斗地主-Android
   */
  SDK_HLDDZ_IOS(17),
  /**
   * 欢乐斗地主-IOS
   */
  SDK_PPKDC_ANDROID(18),
  /**
   * 跑跑卡丁-Android
   */
  SDK_PPKDC_IOS(19),
  /**
   * 跑跑卡丁车-IOS
   */
  SDK_PPKDC_H5_ANDROID(20),
  /**
   * 跑跑卡丁车-Android-H5直播页面
   */
  SDK_PPKDC_H5_IOS(21),
  /**
   * 跑跑卡丁车-IOS-H5直播页面
   */
  SDK_HLDDZ_H5_ANDROID(22),
  /**
   * 欢乐斗地主-Android-H5直播页面
   */
  SDK_HLDDZ_H5_IOS(23),
  /**
   * 欢乐斗地主-IOS-H5直播页面
   */
  SDK_HPJY_ANDROID(24),
  /**
   * 和平精英-Android
   */
  SDK_HPJY_IOS(25),
  /**
   * 和平精英-IOS
   */
  SDK_HPJY_H5_ANDROID(26),
  /**
   * 和平精英h5-Android
   */
  SDK_HPJY_H5_IOS(27),
  /**
   * 和平精英h5-IOS
   */
  EXTERN_WX_MATCH_APPLET_ANDROID(500),
  /**
   * 赛事分享小程序-安卓
   */
  EXTERN_WX_MATCH_APPLET_IOS(501),
  /**
   * 赛事分享小程序-IOS
   */
  EXTERN_DONGXI_ANDROID(502),
  /**
   * 东西部阵营
   */
  EXTERN_DONGXI_IOS(503);

  private final int value;

  private ClientType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
