// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;

public final class DbFetchParam extends Message {

  public static final ByteString DEFAULT_NAME = ByteString.EMPTY;
  public static final ByteString DEFAULT_VALUE = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString name;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString value;

  public DbFetchParam(ByteString name, ByteString value) {
    this.name = name;
    this.value = value;
  }

  private DbFetchParam(Builder builder) {
    this(builder.name, builder.value);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DbFetchParam)) return false;
    DbFetchParam o = (DbFetchParam) other;
    return equals(name, o.name)
        && equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (value != null ? value.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<DbFetchParam> {

    public ByteString name;
    public ByteString value;

    public Builder() {
    }

    public Builder(DbFetchParam message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.value = message.value;
    }

    public Builder name(ByteString name) {
      this.name = name;
      return this;
    }

    public Builder value(ByteString value) {
      this.value = value;
      return this;
    }

    @Override
    public DbFetchParam build() {
      return new DbFetchParam(this);
    }
  }
}
