// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.ProtoEnum;

public enum JUMP_TYPE
    implements ProtoEnum {
  JUMP_TYPE_GAME_LIST(1),
  /**
   * 游戏列表 无参
   */
  JUMP_TYPE_GAME_DETAILS(2),
  /**
   * 游戏详情 gameid
   */
  JUMP_TYPE_INFO_LIST(3),
  /**
   * 资讯列表 无参
   */
  JUMP_TYPE_INFO_DETAILS(4),
  /**
   * 资讯详情 articleid
   */
  JUMP_TYPE_VIDEO_DETAILS(5),
  /**
   * 视频详情 videoid
   */
  JUMP_TYPE_VIDEO_ALBUM_LIST(6),
  /**
   * 视频专辑列表 专辑id
   */
  JUMP_TYPE_URL(7),
  /**
   * 活动地址，URL
   */
  JUMP_TYPE_LIVE(8),
  /**
   * 直播页 roomid
   */
  JUMP_TYPE_QQVIDEO_LIVE(9);

  private final int value;

  private JUMP_TYPE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
