// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;

public final class RecommendItem extends Message {

  public static final ByteString DEFAULT_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_TITLE = ByteString.EMPTY;
  public static final ByteString DEFAULT_AUTHOR = ByteString.EMPTY;
  public static final ByteString DEFAULT_LABEL = ByteString.EMPTY;
  public static final ByteString DEFAULT_PICTURE = ByteString.EMPTY;
  public static final Integer DEFAULT_JUMP_TYPE = 0;
  public static final ByteString DEFAULT_JUMP_MARK = ByteString.EMPTY;
  public static final Integer DEFAULT_ON_TIME = 0;
  public static final Integer DEFAULT_OFF_TIME = 0;
  public static final Integer DEFAULT_DURATION = 0;
  public static final Integer DEFAULT_VIDEO_PV = 0;
  public static final Integer DEFAULT_ONLINE_NUM = 0;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString id;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString title;

  /**
   * 标题
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString author;

  /**
   * 作者
   */
  @ProtoField(tag = 4, type = BYTES)
  public final ByteString label;

  /**
   * 标签
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString picture;

  /**
   * 图片
   */
  @ProtoField(tag = 6, type = UINT32)
  public final Integer jump_type;

  /**
   * 跳转类型
   */
  @ProtoField(tag = 7, type = BYTES)
  public final ByteString jump_mark;

  /**
   * 跳转标识
   */
  @ProtoField(tag = 8, type = UINT32)
  public final Integer on_time;

  /**
   * 上架时间
   */
  @ProtoField(tag = 9, type = UINT32)
  public final Integer off_time;

  /**
   * 下架时间
   */
  @ProtoField(tag = 10, type = UINT32)
  public final Integer duration;

  /**
   * 视频时长
   */
  @ProtoField(tag = 11, type = UINT32)
  public final Integer video_pv;

  /**
   * 视频点击量
   */
  @ProtoField(tag = 12, type = UINT32)
  public final Integer online_num;

  public RecommendItem(ByteString id, ByteString title, ByteString author, ByteString label, ByteString picture, Integer jump_type, ByteString jump_mark, Integer on_time, Integer off_time, Integer duration, Integer video_pv, Integer online_num) {
    this.id = id;
    this.title = title;
    this.author = author;
    this.label = label;
    this.picture = picture;
    this.jump_type = jump_type;
    this.jump_mark = jump_mark;
    this.on_time = on_time;
    this.off_time = off_time;
    this.duration = duration;
    this.video_pv = video_pv;
    this.online_num = online_num;
  }

  private RecommendItem(Builder builder) {
    this(builder.id, builder.title, builder.author, builder.label, builder.picture, builder.jump_type, builder.jump_mark, builder.on_time, builder.off_time, builder.duration, builder.video_pv, builder.online_num);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RecommendItem)) return false;
    RecommendItem o = (RecommendItem) other;
    return equals(id, o.id)
        && equals(title, o.title)
        && equals(author, o.author)
        && equals(label, o.label)
        && equals(picture, o.picture)
        && equals(jump_type, o.jump_type)
        && equals(jump_mark, o.jump_mark)
        && equals(on_time, o.on_time)
        && equals(off_time, o.off_time)
        && equals(duration, o.duration)
        && equals(video_pv, o.video_pv)
        && equals(online_num, o.online_num);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = id != null ? id.hashCode() : 0;
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (author != null ? author.hashCode() : 0);
      result = result * 37 + (label != null ? label.hashCode() : 0);
      result = result * 37 + (picture != null ? picture.hashCode() : 0);
      result = result * 37 + (jump_type != null ? jump_type.hashCode() : 0);
      result = result * 37 + (jump_mark != null ? jump_mark.hashCode() : 0);
      result = result * 37 + (on_time != null ? on_time.hashCode() : 0);
      result = result * 37 + (off_time != null ? off_time.hashCode() : 0);
      result = result * 37 + (duration != null ? duration.hashCode() : 0);
      result = result * 37 + (video_pv != null ? video_pv.hashCode() : 0);
      result = result * 37 + (online_num != null ? online_num.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RecommendItem> {

    public ByteString id;
    public ByteString title;
    public ByteString author;
    public ByteString label;
    public ByteString picture;
    public Integer jump_type;
    public ByteString jump_mark;
    public Integer on_time;
    public Integer off_time;
    public Integer duration;
    public Integer video_pv;
    public Integer online_num;

    public Builder() {
    }

    public Builder(RecommendItem message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
      this.title = message.title;
      this.author = message.author;
      this.label = message.label;
      this.picture = message.picture;
      this.jump_type = message.jump_type;
      this.jump_mark = message.jump_mark;
      this.on_time = message.on_time;
      this.off_time = message.off_time;
      this.duration = message.duration;
      this.video_pv = message.video_pv;
      this.online_num = message.online_num;
    }

    public Builder id(ByteString id) {
      this.id = id;
      return this;
    }

    public Builder title(ByteString title) {
      this.title = title;
      return this;
    }

    /**
     * 标题
     */
    public Builder author(ByteString author) {
      this.author = author;
      return this;
    }

    /**
     * 作者
     */
    public Builder label(ByteString label) {
      this.label = label;
      return this;
    }

    /**
     * 标签
     */
    public Builder picture(ByteString picture) {
      this.picture = picture;
      return this;
    }

    /**
     * 图片
     */
    public Builder jump_type(Integer jump_type) {
      this.jump_type = jump_type;
      return this;
    }

    /**
     * 跳转类型
     */
    public Builder jump_mark(ByteString jump_mark) {
      this.jump_mark = jump_mark;
      return this;
    }

    /**
     * 跳转标识
     */
    public Builder on_time(Integer on_time) {
      this.on_time = on_time;
      return this;
    }

    /**
     * 上架时间
     */
    public Builder off_time(Integer off_time) {
      this.off_time = off_time;
      return this;
    }

    /**
     * 下架时间
     */
    public Builder duration(Integer duration) {
      this.duration = duration;
      return this;
    }

    /**
     * 视频时长
     */
    public Builder video_pv(Integer video_pv) {
      this.video_pv = video_pv;
      return this;
    }

    /**
     * 视频点击量
     */
    public Builder online_num(Integer online_num) {
      this.online_num = online_num;
      return this;
    }

    @Override
    public RecommendItem build() {
      return new RecommendItem(this);
    }
  }
}
