// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.ProtoEnum;

public enum SOURCE_TYPE
    implements ProtoEnum {
  SOURCE_TYPE_VIEDO_DETAIL_PAGE(1),
  /**
   * 视频详情页
   */
  SOURCE_TYPE_GAME_DETAIL_PAGE(2),
  /**
   * 游戏详情页
   */
  SOURCE_TYPE_HOME_PAGE_GAMERECOMMEND(3),
  /**
   * 首页游戏推荐
   */
  SOURCE_TYPE_LIVE_DETAILS(4),
  /**
   * 直播详情页
   */
  SOURCE_TYPE_GAME_LIVE_LIST(5),
  /**
   * 按游戏类型拉取直播列表-指定游戏-分页
   */
  SOURCE_TYPE_FRONT_PAGE_LIVE_LIST(6),
  /**
   * 首页直播列表-所有游戏-数量可配
   */
  SOURCE_TYPE_LIVE_ROOM_RECOMM_LIST(7),
  /**
   * 主播房间推荐直播列表-指定游戏-数量可配
   */
  SOURCE_TYPE_HOMEPAGE_CAROUSEL(8),
  /**
   * 首页轮播图
   */
  SOURCE_TYPE_H5_LIVE(9),
  /**
   * H5直播页面
   */
  SOURCE_TYPE_H5_LIVE_TTXD(10);

  private final int value;

  private SOURCE_TYPE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
