// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.ProtoEnum;

public enum STREAM_TYPE
    implements ProtoEnum {
  E_STREAM_TYPE_EZ(0),
  /**
   * 鹅掌视频流
   */
  E_STREAM_TYPE_QQVIDEO(1);

  private final int value;

  private STREAM_TYPE(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
