// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\common.proto
package com.tencent.protocol.tga.common;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;

public final class VideoItem extends Message {

  public static final ByteString DEFAULT_VID = ByteString.EMPTY;
  public static final ByteString DEFAULT_TITLE = ByteString.EMPTY;
  public static final ByteString DEFAULT_AUTHOR = ByteString.EMPTY;
  public static final ByteString DEFAULT_DESCRIPTION = ByteString.EMPTY;
  public static final ByteString DEFAULT_COVER_IMAGE_228_128 = ByteString.EMPTY;
  public static final Integer DEFAULT_CREATE_TIME = 0;
  public static final Integer DEFAULT_DURATION = 0;
  public static final Integer DEFAULT_VIDEO_PV = 0;
  public static final ByteString DEFAULT_GAME_ID = ByteString.EMPTY;
  public static final ByteString DEFAULT_COVER_IMAGE_496_280 = ByteString.EMPTY;
  public static final ByteString DEFAULT_GAME_NAME = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString vid;

  /**
   * 视频ID
   */
  @ProtoField(tag = 2, type = BYTES)
  public final ByteString title;

  /**
   * 标题
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString author;

  /**
   * 作者
   */
  @ProtoField(tag = 4, type = BYTES)
  public final ByteString description;

  /**
   * 描述
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString cover_image_228_128;

  /**
   * 图片
   */
  @ProtoField(tag = 6, type = UINT32)
  public final Integer create_time;

  /**
   * 上架时间
   */
  @ProtoField(tag = 7, type = UINT32)
  public final Integer duration;

  /**
   * 视频时长
   */
  @ProtoField(tag = 8, type = UINT32)
  public final Integer video_pv;

  /**
   * 视频点击量
   */
  @ProtoField(tag = 9, type = BYTES)
  public final ByteString game_id;

  /**
   * 游戏ID
   */
  @ProtoField(tag = 10, type = BYTES)
  public final ByteString cover_image_496_280;

  /**
   * 图片
   */
  @ProtoField(tag = 11, type = BYTES)
  public final ByteString game_name;

  public VideoItem(ByteString vid, ByteString title, ByteString author, ByteString description, ByteString cover_image_228_128, Integer create_time, Integer duration, Integer video_pv, ByteString game_id, ByteString cover_image_496_280, ByteString game_name) {
    this.vid = vid;
    this.title = title;
    this.author = author;
    this.description = description;
    this.cover_image_228_128 = cover_image_228_128;
    this.create_time = create_time;
    this.duration = duration;
    this.video_pv = video_pv;
    this.game_id = game_id;
    this.cover_image_496_280 = cover_image_496_280;
    this.game_name = game_name;
  }

  private VideoItem(Builder builder) {
    this(builder.vid, builder.title, builder.author, builder.description, builder.cover_image_228_128, builder.create_time, builder.duration, builder.video_pv, builder.game_id, builder.cover_image_496_280, builder.game_name);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VideoItem)) return false;
    VideoItem o = (VideoItem) other;
    return equals(vid, o.vid)
        && equals(title, o.title)
        && equals(author, o.author)
        && equals(description, o.description)
        && equals(cover_image_228_128, o.cover_image_228_128)
        && equals(create_time, o.create_time)
        && equals(duration, o.duration)
        && equals(video_pv, o.video_pv)
        && equals(game_id, o.game_id)
        && equals(cover_image_496_280, o.cover_image_496_280)
        && equals(game_name, o.game_name);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = vid != null ? vid.hashCode() : 0;
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (author != null ? author.hashCode() : 0);
      result = result * 37 + (description != null ? description.hashCode() : 0);
      result = result * 37 + (cover_image_228_128 != null ? cover_image_228_128.hashCode() : 0);
      result = result * 37 + (create_time != null ? create_time.hashCode() : 0);
      result = result * 37 + (duration != null ? duration.hashCode() : 0);
      result = result * 37 + (video_pv != null ? video_pv.hashCode() : 0);
      result = result * 37 + (game_id != null ? game_id.hashCode() : 0);
      result = result * 37 + (cover_image_496_280 != null ? cover_image_496_280.hashCode() : 0);
      result = result * 37 + (game_name != null ? game_name.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<VideoItem> {

    public ByteString vid;
    public ByteString title;
    public ByteString author;
    public ByteString description;
    public ByteString cover_image_228_128;
    public Integer create_time;
    public Integer duration;
    public Integer video_pv;
    public ByteString game_id;
    public ByteString cover_image_496_280;
    public ByteString game_name;

    public Builder() {
    }

    public Builder(VideoItem message) {
      super(message);
      if (message == null) return;
      this.vid = message.vid;
      this.title = message.title;
      this.author = message.author;
      this.description = message.description;
      this.cover_image_228_128 = message.cover_image_228_128;
      this.create_time = message.create_time;
      this.duration = message.duration;
      this.video_pv = message.video_pv;
      this.game_id = message.game_id;
      this.cover_image_496_280 = message.cover_image_496_280;
      this.game_name = message.game_name;
    }

    public Builder vid(ByteString vid) {
      this.vid = vid;
      return this;
    }

    /**
     * 视频ID
     */
    public Builder title(ByteString title) {
      this.title = title;
      return this;
    }

    /**
     * 标题
     */
    public Builder author(ByteString author) {
      this.author = author;
      return this;
    }

    /**
     * 作者
     */
    public Builder description(ByteString description) {
      this.description = description;
      return this;
    }

    /**
     * 描述
     */
    public Builder cover_image_228_128(ByteString cover_image_228_128) {
      this.cover_image_228_128 = cover_image_228_128;
      return this;
    }

    /**
     * 图片
     */
    public Builder create_time(Integer create_time) {
      this.create_time = create_time;
      return this;
    }

    /**
     * 上架时间
     */
    public Builder duration(Integer duration) {
      this.duration = duration;
      return this;
    }

    /**
     * 视频时长
     */
    public Builder video_pv(Integer video_pv) {
      this.video_pv = video_pv;
      return this;
    }

    /**
     * 视频点击量
     */
    public Builder game_id(ByteString game_id) {
      this.game_id = game_id;
      return this;
    }

    /**
     * 游戏ID
     */
    public Builder cover_image_496_280(ByteString cover_image_496_280) {
      this.cover_image_496_280 = cover_image_496_280;
      return this;
    }

    /**
     * 图片
     */
    public Builder game_name(ByteString game_name) {
      this.game_name = game_name;
      return this;
    }

    @Override
    public VideoItem build() {
      return new VideoItem(this);
    }
  }
}
