// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\hpjy_update_roominfo.proto
package com.tencent.protocol.tga.hpjy_update_roominfo;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;

import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * BUSINESS_TYPE_HPJY_NOTIFY_LIVE_OFFLINE           = 214; //通知直播下线-多赛事房间广播
 */
public final class NotifyLiveOffline extends Message {

  public static final Integer DEFAULT_SOURCE_ID = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer source_id;

  public NotifyLiveOffline(Integer source_id) {
    this.source_id = source_id;
  }

  private NotifyLiveOffline(Builder builder) {
    this(builder.source_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NotifyLiveOffline)) return false;
    return equals(source_id, ((NotifyLiveOffline) other).source_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = source_id != null ? source_id.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<NotifyLiveOffline> {

    public Integer source_id;

    public Builder() {
    }

    public Builder(NotifyLiveOffline message) {
      super(message);
      if (message == null) return;
      this.source_id = message.source_id;
    }

    public Builder source_id(Integer source_id) {
      this.source_id = source_id;
      return this;
    }

    @Override
    public NotifyLiveOffline build() {
      checkRequiredFields();
      return new NotifyLiveOffline(this);
    }
  }
}
