// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\hpjy_update_roominfo.proto
package com.tencent.protocol.tga.hpjy_update_roominfo;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.tga.Message.Label.REPEATED;

/**
 * BUSINESS_TYPE_HPJY_UPDATE_LIVE_INFO              = 213; //更新直播信息-多赛事房间广播
 */
public final class UpdateRoomInfoList extends Message {

  public static final List<UpdateRoomInfo> DEFAULT_ROOM_LIST = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = UpdateRoomInfo.class)
  public final List<UpdateRoomInfo> room_list;

  public UpdateRoomInfoList(List<UpdateRoomInfo> room_list) {
    this.room_list = immutableCopyOf(room_list);
  }

  private UpdateRoomInfoList(Builder builder) {
    this(builder.room_list);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UpdateRoomInfoList)) return false;
    return equals(room_list, ((UpdateRoomInfoList) other).room_list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = room_list != null ? room_list.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<UpdateRoomInfoList> {

    public List<UpdateRoomInfo> room_list;

    public Builder() {
    }

    public Builder(UpdateRoomInfoList message) {
      super(message);
      if (message == null) return;
      this.room_list = copyOf(message.room_list);
    }

    public Builder room_list(List<UpdateRoomInfo> room_list) {
      this.room_list = checkForNulls(room_list);
      return this;
    }

    @Override
    public UpdateRoomInfoList build() {
      return new UpdateRoomInfoList(this);
    }
  }
}
