// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.ProtoEnum;

public enum conn_cmd_types
    implements ProtoEnum {
  CMD_CONN(4096);

  private final int value;

  private conn_cmd_types(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
