// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.ProtoEnum;

public enum conn_subcmd
    implements ProtoEnum {
  SUBCMD_CONN_LOGIN(1),
  /**
   * 登录请求。
   */
  SUBCMD_CONN_LOGOUT(2),
  /**
   * 退出请求。
   */
  SUBCMD_CONN_HELLO(3),
  /**
   * 长连接心跳
   */
  SUBCMD_CONN_PUSH(4),
  /**
   * 消息push
   */
  SUBCMD_CONN_ROOM_ENTER(17),
  /**
   * 进房请求。
   */
  SUBCMD_CONN_ROOM_LEAVE(18),
  /**
   * 退房请求。
   */
  SUBCMD_CONN_ROOM_HELLO(19);

  private final int value;

  private conn_subcmd(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
