// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;

import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * SUBCMD_CONN_HELLO = 0x3;	//长连接心跳
 */
public final class HelloReq extends Message {

  public static final Integer DEFAULT_CUR_TIME = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer cur_time;

  public HelloReq(Integer cur_time) {
    this.cur_time = cur_time;
  }

  private HelloReq(Builder builder) {
    this(builder.cur_time);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HelloReq)) return false;
    return equals(cur_time, ((HelloReq) other).cur_time);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = cur_time != null ? cur_time.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<HelloReq> {

    public Integer cur_time;

    public Builder() {
    }

    public Builder(HelloReq message) {
      super(message);
      if (message == null) return;
      this.cur_time = message.cur_time;
    }

    public Builder cur_time(Integer cur_time) {
      this.cur_time = cur_time;
      return this;
    }

    @Override
    public HelloReq build() {
      checkRequiredFields();
      return new HelloReq(this);
    }
  }
}
