// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;

import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class HelloRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final Integer DEFAULT_HELLO_TIME = 0;
  public static final Integer DEFAULT_CLOSE_TCP = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  /**
   * 0表成功，1表示失败
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer hello_time;

  @ProtoField(tag = 3, type = UINT32)
  public final Integer close_tcp;

  public HelloRsp(Integer result, Integer hello_time, Integer close_tcp) {
    this.result = result;
    this.hello_time = hello_time;
    this.close_tcp = close_tcp;
  }

  private HelloRsp(Builder builder) {
    this(builder.result, builder.hello_time, builder.close_tcp);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HelloRsp)) return false;
    HelloRsp o = (HelloRsp) other;
    return equals(result, o.result)
        && equals(hello_time, o.hello_time)
        && equals(close_tcp, o.close_tcp);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (hello_time != null ? hello_time.hashCode() : 0);
      result = result * 37 + (close_tcp != null ? close_tcp.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<HelloRsp> {

    public Integer result;
    public Integer hello_time;
    public Integer close_tcp;

    public Builder() {
    }

    public Builder(HelloRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.hello_time = message.hello_time;
      this.close_tcp = message.close_tcp;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 0表成功，1表示失败
     */
    public Builder hello_time(Integer hello_time) {
      this.hello_time = hello_time;
      return this;
    }

    public Builder close_tcp(Integer close_tcp) {
      this.close_tcp = close_tcp;
      return this;
    }

    @Override
    public HelloRsp build() {
      checkRequiredFields();
      return new HelloRsp(this);
    }
  }
}
