// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;

/**
 * SUBCMD_CONN_QTLOGIN 0x1票据登录
 */
public final class LoginReq extends Message {

  public static final ByteString DEFAULT_OPENID = ByteString.EMPTY;
  public static final ByteString DEFAULT_UUID = ByteString.EMPTY;
  public static final ByteString DEFAULT_ACCESS_TOKEN = ByteString.EMPTY;
  public static final ByteString DEFAULT_MACHINE_CODE = ByteString.EMPTY;
  public static final Integer DEFAULT_NETWORK_TYPE = 0;
  public static final ByteString DEFAULT_JFGAMEID = ByteString.EMPTY;
  public static final ByteString DEFAULT_GAMEID = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString openid;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString uuid;

  @ProtoField(tag = 3, type = BYTES)
  public final ByteString access_token;

  @ProtoField(tag = 4, type = BYTES)
  public final ByteString machine_code;

  @ProtoField(tag = 5, type = UINT32)
  public final Integer network_type;

  /**
   * 0：wifi，1：移动网络
   */
  @ProtoField(tag = 6, type = BYTES)
  public final ByteString jfgameid;

  /**
   * 经分上报用，和经分同事协定
   */
  @ProtoField(tag = 7, type = BYTES)
  public final ByteString gameid;

  public LoginReq(ByteString openid, ByteString uuid, ByteString access_token, ByteString machine_code, Integer network_type, ByteString jfgameid, ByteString gameid) {
    this.openid = openid;
    this.uuid = uuid;
    this.access_token = access_token;
    this.machine_code = machine_code;
    this.network_type = network_type;
    this.jfgameid = jfgameid;
    this.gameid = gameid;
  }

  private LoginReq(Builder builder) {
    this(builder.openid, builder.uuid, builder.access_token, builder.machine_code, builder.network_type, builder.jfgameid, builder.gameid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginReq)) return false;
    LoginReq o = (LoginReq) other;
    return equals(openid, o.openid)
        && equals(uuid, o.uuid)
        && equals(access_token, o.access_token)
        && equals(machine_code, o.machine_code)
        && equals(network_type, o.network_type)
        && equals(jfgameid, o.jfgameid)
        && equals(gameid, o.gameid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = openid != null ? openid.hashCode() : 0;
      result = result * 37 + (uuid != null ? uuid.hashCode() : 0);
      result = result * 37 + (access_token != null ? access_token.hashCode() : 0);
      result = result * 37 + (machine_code != null ? machine_code.hashCode() : 0);
      result = result * 37 + (network_type != null ? network_type.hashCode() : 0);
      result = result * 37 + (jfgameid != null ? jfgameid.hashCode() : 0);
      result = result * 37 + (gameid != null ? gameid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LoginReq> {

    public ByteString openid;
    public ByteString uuid;
    public ByteString access_token;
    public ByteString machine_code;
    public Integer network_type;
    public ByteString jfgameid;
    public ByteString gameid;

    public Builder() {
    }

    public Builder(LoginReq message) {
      super(message);
      if (message == null) return;
      this.openid = message.openid;
      this.uuid = message.uuid;
      this.access_token = message.access_token;
      this.machine_code = message.machine_code;
      this.network_type = message.network_type;
      this.jfgameid = message.jfgameid;
      this.gameid = message.gameid;
    }

    public Builder openid(ByteString openid) {
      this.openid = openid;
      return this;
    }

    public Builder uuid(ByteString uuid) {
      this.uuid = uuid;
      return this;
    }

    public Builder access_token(ByteString access_token) {
      this.access_token = access_token;
      return this;
    }

    public Builder machine_code(ByteString machine_code) {
      this.machine_code = machine_code;
      return this;
    }

    public Builder network_type(Integer network_type) {
      this.network_type = network_type;
      return this;
    }

    /**
     * 0：wifi，1：移动网络
     */
    public Builder jfgameid(ByteString jfgameid) {
      this.jfgameid = jfgameid;
      return this;
    }

    /**
     * 经分上报用，和经分同事协定
     */
    public Builder gameid(ByteString gameid) {
      this.gameid = gameid;
      return this;
    }

    @Override
    public LoginReq build() {
      return new LoginReq(this);
    }
  }
}
