// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;

public final class LogoutReq extends Message {

  public static final ByteString DEFAULT_OPENID = ByteString.EMPTY;
  public static final ByteString DEFAULT_UUID = ByteString.EMPTY;
  public static final ByteString DEFAULT_ACCESS_TOKEN = ByteString.EMPTY;
  public static final ByteString DEFAULT_MACHINE_CODE = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString openid;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString uuid;

  @ProtoField(tag = 3, type = BYTES)
  public final ByteString access_token;

  @ProtoField(tag = 4, type = BYTES)
  public final ByteString machine_code;

  public LogoutReq(ByteString openid, ByteString uuid, ByteString access_token, ByteString machine_code) {
    this.openid = openid;
    this.uuid = uuid;
    this.access_token = access_token;
    this.machine_code = machine_code;
  }

  private LogoutReq(Builder builder) {
    this(builder.openid, builder.uuid, builder.access_token, builder.machine_code);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LogoutReq)) return false;
    LogoutReq o = (LogoutReq) other;
    return equals(openid, o.openid)
        && equals(uuid, o.uuid)
        && equals(access_token, o.access_token)
        && equals(machine_code, o.machine_code);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = openid != null ? openid.hashCode() : 0;
      result = result * 37 + (uuid != null ? uuid.hashCode() : 0);
      result = result * 37 + (access_token != null ? access_token.hashCode() : 0);
      result = result * 37 + (machine_code != null ? machine_code.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LogoutReq> {

    public ByteString openid;
    public ByteString uuid;
    public ByteString access_token;
    public ByteString machine_code;

    public Builder() {
    }

    public Builder(LogoutReq message) {
      super(message);
      if (message == null) return;
      this.openid = message.openid;
      this.uuid = message.uuid;
      this.access_token = message.access_token;
      this.machine_code = message.machine_code;
    }

    public Builder openid(ByteString openid) {
      this.openid = openid;
      return this;
    }

    public Builder uuid(ByteString uuid) {
      this.uuid = uuid;
      return this;
    }

    public Builder access_token(ByteString access_token) {
      this.access_token = access_token;
      return this;
    }

    public Builder machine_code(ByteString machine_code) {
      this.machine_code = machine_code;
      return this;
    }

    @Override
    public LogoutReq build() {
      return new LogoutReq(this);
    }
  }
}
