// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Label.REQUIRED;

/**
 * SUBCMD_CONN_ROOM_ENTER	= 0x11	进房请求。
 */
public final class Room_EnterReq extends Message {

  public static final ByteString DEFAULT_ROOMID = ByteString.EMPTY;
  public static final ByteString DEFAULT_USERID = ByteString.EMPTY;
  public static final ByteString DEFAULT_NICK = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES, label = REQUIRED)
  public final ByteString roomid;

  @ProtoField(tag = 2, type = BYTES, label = REQUIRED)
  public final ByteString userid;

  @ProtoField(tag = 3, type = BYTES)
  public final ByteString nick;

  public Room_EnterReq(ByteString roomid, ByteString userid, ByteString nick) {
    this.roomid = roomid;
    this.userid = userid;
    this.nick = nick;
  }

  private Room_EnterReq(Builder builder) {
    this(builder.roomid, builder.userid, builder.nick);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Room_EnterReq)) return false;
    Room_EnterReq o = (Room_EnterReq) other;
    return equals(roomid, o.roomid)
        && equals(userid, o.userid)
        && equals(nick, o.nick);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = roomid != null ? roomid.hashCode() : 0;
      result = result * 37 + (userid != null ? userid.hashCode() : 0);
      result = result * 37 + (nick != null ? nick.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Room_EnterReq> {

    public ByteString roomid;
    public ByteString userid;
    public ByteString nick;

    public Builder() {
    }

    public Builder(Room_EnterReq message) {
      super(message);
      if (message == null) return;
      this.roomid = message.roomid;
      this.userid = message.userid;
      this.nick = message.nick;
    }

    public Builder roomid(ByteString roomid) {
      this.roomid = roomid;
      return this;
    }

    public Builder userid(ByteString userid) {
      this.userid = userid;
      return this;
    }

    public Builder nick(ByteString nick) {
      this.nick = nick;
      return this;
    }

    @Override
    public Room_EnterReq build() {
      checkRequiredFields();
      return new Room_EnterReq(this);
    }
  }
}
