// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.STRING;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class Room_EnterRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final String DEFAULT_ERRMSG = "";
  public static final ByteString DEFAULT_ROOMID = ByteString.EMPTY;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  /**
   * 请求结果， 0：进房成功， 1：进房失败，2：房间人数满，3：没有权限进房
   */
  @ProtoField(tag = 2, type = STRING)
  public final String errMsg;

  /**
   * 错误信息
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString roomid;

  public Room_EnterRsp(Integer result, String errMsg, ByteString roomid) {
    this.result = result;
    this.errMsg = errMsg;
    this.roomid = roomid;
  }

  private Room_EnterRsp(Builder builder) {
    this(builder.result, builder.errMsg, builder.roomid);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Room_EnterRsp)) return false;
    Room_EnterRsp o = (Room_EnterRsp) other;
    return equals(result, o.result)
        && equals(errMsg, o.errMsg)
        && equals(roomid, o.roomid);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (errMsg != null ? errMsg.hashCode() : 0);
      result = result * 37 + (roomid != null ? roomid.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Room_EnterRsp> {

    public Integer result;
    public String errMsg;
    public ByteString roomid;

    public Builder() {
    }

    public Builder(Room_EnterRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.errMsg = message.errMsg;
      this.roomid = message.roomid;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 请求结果， 0：进房成功， 1：进房失败，2：房间人数满，3：没有权限进房
     */
    public Builder errMsg(String errMsg) {
      this.errMsg = errMsg;
      return this;
    }

    /**
     * 错误信息
     */
    public Builder roomid(ByteString roomid) {
      this.roomid = roomid;
      return this;
    }

    @Override
    public Room_EnterRsp build() {
      checkRequiredFields();
      return new Room_EnterRsp(this);
    }
  }
}
