// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;

import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class Room_HelloRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final Integer DEFAULT_HELLO_TIMESPAN = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  /**
   * 请求结果， 0：成功，1：重新进房
   */
  @ProtoField(tag = 2, type = UINT32)
  public final Integer hello_timespan;

  public Room_HelloRsp(Integer result, Integer hello_timespan) {
    this.result = result;
    this.hello_timespan = hello_timespan;
  }

  private Room_HelloRsp(Builder builder) {
    this(builder.result, builder.hello_timespan);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Room_HelloRsp)) return false;
    Room_HelloRsp o = (Room_HelloRsp) other;
    return equals(result, o.result)
        && equals(hello_timespan, o.hello_timespan);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (hello_timespan != null ? hello_timespan.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Room_HelloRsp> {

    public Integer result;
    public Integer hello_timespan;

    public Builder() {
    }

    public Builder(Room_HelloRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.hello_timespan = message.hello_timespan;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 请求结果， 0：成功，1：重新进房
     */
    public Builder hello_timespan(Integer hello_timespan) {
      this.hello_timespan = hello_timespan;
      return this;
    }

    @Override
    public Room_HelloRsp build() {
      checkRequiredFields();
      return new Room_HelloRsp(this);
    }
  }
}
