// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.ProtoEnum;

public enum room_type
    implements ProtoEnum {
  ROOM_TYPE_MATCH_ROOM(0),
  /**
   * 赛事房间
   */
  ROOM_TYPE_BALCONY_ROOM(1);

  private final int value;

  private room_type(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
