// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\conn.proto
package com.tencent.protocol.tga.conn;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;

import static com.squareup.tga.Message.Datatype.STRING;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class Room_LeaveRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final String DEFAULT_ERRMSG = "";

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  /**
   * 请求结果
   */
  @ProtoField(tag = 2, type = STRING)
  public final String errMsg;

  public Room_LeaveRsp(Integer result, String errMsg) {
    this.result = result;
    this.errMsg = errMsg;
  }

  private Room_LeaveRsp(Builder builder) {
    this(builder.result, builder.errMsg);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Room_LeaveRsp)) return false;
    Room_LeaveRsp o = (Room_LeaveRsp) other;
    return equals(result, o.result)
        && equals(errMsg, o.errMsg);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (errMsg != null ? errMsg.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Room_LeaveRsp> {

    public Integer result;
    public String errMsg;

    public Builder() {
    }

    public Builder(Room_LeaveRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.errMsg = message.errMsg;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    /**
     * 请求结果
     */
    public Builder errMsg(String errMsg) {
      this.errMsg = errMsg;
      return this;
    }

    @Override
    public Room_LeaveRsp build() {
      checkRequiredFields();
      return new Room_LeaveRsp(this);
    }
  }
}
