// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\vod_op.proto
package com.tencent.protocol.tga.vod_op;

import com.squareup.tga.ProtoEnum;

public enum CMD
    implements ProtoEnum {
  CMD_VOD_OP(4166);

  private final int value;

  private CMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
