// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\vod_op.proto
package com.tencent.protocol.tga.vod_op;

import com.squareup.tga.ProtoEnum;

public enum DianZanOp
    implements ProtoEnum {
  kZan(1),
  /**
   * 点赞操作
   */
  kUnZan(2);

  private final int value;

  private DianZanOp(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
