// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\vod_op.proto
package com.tencent.protocol.tga.vod_op;

import com.squareup.tga.Message;
import com.squareup.tga.ProtoField;
import okiotga.ByteString;

import static com.squareup.tga.Message.Datatype.BYTES;
import static com.squareup.tga.Message.Datatype.UINT32;
import static com.squareup.tga.Message.Label.REQUIRED;

public final class SendDanmuRsp extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final ByteString DEFAULT_ERR_MSG = ByteString.EMPTY;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer result;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString err_msg;

  public SendDanmuRsp(Integer result, ByteString err_msg) {
    this.result = result;
    this.err_msg = err_msg;
  }

  private SendDanmuRsp(Builder builder) {
    this(builder.result, builder.err_msg);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SendDanmuRsp)) return false;
    SendDanmuRsp o = (SendDanmuRsp) other;
    return equals(result, o.result)
        && equals(err_msg, o.err_msg);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (err_msg != null ? err_msg.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SendDanmuRsp> {

    public Integer result;
    public ByteString err_msg;

    public Builder() {
    }

    public Builder(SendDanmuRsp message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.err_msg = message.err_msg;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    public Builder err_msg(ByteString err_msg) {
      this.err_msg = err_msg;
      return this;
    }

    @Override
    public SendDanmuRsp build() {
      checkRequiredFields();
      return new SendDanmuRsp(this);
    }
  }
}
