// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\vod_op.proto
package com.tencent.protocol.tga.vod_op;

import com.squareup.tga.ProtoEnum;

public enum SUBCMD
    implements ProtoEnum {
  SUBCMD_SEND_DANMU(1),
  /**
   * 发送弹幕
   */
  SUBCMD_DIAN_ZAN(2);

  private final int value;

  private SUBCMD(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
