// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: .\\recommend.proto
package com.tencent.tga.liveplugin.poptv.bean;

import com.squareup.tga.ProtoEnum;

public enum BannerType
    implements ProtoEnum {
  BannerNothing(0),
  BannerSeeingFriendList(1),
  /**
   * 观看过
   */
  BannerSawFriendList(2),
  BannerCustomBanner(3);

  private final int value;

  private BannerType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
